name: easy_web_view
description: A super simple webview for Flutter Web and Mobile
version: 2.0.0
homepage: https://github.com/rodydavis/easy_web_view
repository: https://github.com/rodydavis/plugins
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.9
  html2md: ^1.2.5
  http: ^0.13.4
  markdown: ^4.0.1
  url_launcher: ^6.0.17
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
